apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-backend
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registry-backend
  template:
    metadata:
      labels:
        app: registry-backend
        transcode: http
    spec:
      serviceAccountName: api-registry
      containers:
      - name: registry-backend
        image: gcr.io/wangyh-playground/registry-backend-noproxy:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
#          protocol: TCP
#          name: grpc